services:
  battlebitminigames:
    container_name: battlebitminigames
    image: battlebitminigames
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # - "./bin/Debug/net6.0/appsettings.json:/app/appsettings.json"
      - "./appsettings.json:/app/appsettings.json"
    ports:
      - "30001:30001/tcp"
    networks:
      - battlebit

networks:
  battlebit: