services:
  battlebitminigames:
    image: battlebitminigames
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./appsettings.json:/app/appsettings.json"
    networks:
      - battlebit

networks:
  battlebit: